<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">


    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}" />
            </geometry>
            <origin xyz="0 0 ${imu_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.002" x="${imu_length}" y="${imu_width}" z="${imu_height}"
                           o_xyz="0 0 ${imu_height / 2.0}" o_rpy="0 0 0" />
    </link>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
    </joint>
</robot>