<?xml version="1.0"?>
<robot name="AGV_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu">
      </plugin>
    </gazebo>
    <gazebo>
      <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
        <render_engine>ogre2</render_engine>
      </plugin>
      <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
        <parameters>$(find agvbot_controller)/config/mecanum_controller.yaml</parameters>
      </plugin>
    </gazebo>
  <!-- IMU -->
  <gazebo reference="imu_link">
    <sensor name="imu" type="imu">
        <always_on>true</always_on>
        <update_rate>15.0</update_rate>
        <gz_frame_id>imu_link</gz_frame_id>
        <topic>imu</topic>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
    </sensor>
  </gazebo>

   <!-- 2D Laser Sensor -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <topic>scan</topic>
      <update_rate>5.0</update_rate>
      <gz_frame_id>lidar_link</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.00000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>12.0</max>
          <resolution>0.02</resolution>
        </range>
        <!-- <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise> -->
      </lidar>
    </sensor>
  </gazebo>


<!--     
    <gazebo>
     <plugin 
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
          <joint_name>front_left_wheel_joint</joint_name>
          <joint_name>front_right_wheel_joint</joint_name>
          <joint_name>back_left_wheel_joint</joint_name>
          <joint_name>back_right_wheel_joint</joint_name>
      </plugin>
   </gazebo>
    <gazebo>
      <plugin
          filename="gz-sim-mecanum-drive-system"
          name="gz::sim::systems::MecanumDrive">
          <front_left_joint>front_left_wheel_joint</front_left_joint>
          <front_right_joint>front_right_wheel_joint</front_right_joint>
          <back_left_joint>back_left_wheel_joint</back_left_joint>
          <back_right_joint>back_right_wheel_joint</back_right_joint>
          <odom_frame_id>odom</odom_frame_id>
          <frame_id>odom</frame_id>
          <enable_odom_tf>true</enable_odom_tf>
          <child_frame_id>base_footprint</child_frame_id>
          <wheel_separation>${base_width  + wheel_length}</wheel_separation>
          <wheelbase>${(2 * base_length) / 2.5}</wheelbase>
          <wheel_radius>0.05</wheel_radius>
          <min_acceleration>-5</min_acceleration>
          <max_acceleration>5</max_acceleration>
        </plugin>

  </gazebo> -->


</robot>