<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="imu_length" value="0.01" />
    <xacro:property name="imu_width" value="0.01" />
    <xacro:property name="imu_height" value="0.002" />
    <xacro:property name="lidar_radius" value="0.025" />
    <xacro:property name="lidar_length" value="0.05" />

    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="15.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

</robot>
